- .gitlab-ci.yml
> Added .gitlab-ci.yml

- src/assets/index.html
> Added overflow hidden to prevent overscrolling on mac systems

- src/app/Code.tsx
> feat: line numbers

- src/Colors.tsx
- src/Graph/index.ts
- src/editor/code/Explorer.tsx
- src/editor/code/style/Explorer.tsx
- src/editor/code/utils/index.ts
- code style fixes
- highlighting
- multi-level searching
- automatic level expanding
- keyboard support
> Improved code explorer search, keyboard, highlighting and multi-level searching

- src/Graf/Graf.tsx
- src/Graf/Node/ActiveNode/TopNodeMenu.tsx
Manually hide menu if this is wanted #372
> 🚸 hide menu, improve error styles

- packages/editor/src/DiffEditor/index.tsx
- packages/editor/src/shared/components/Select.tsx
- packages/editor/src/shared/components/index.tsx
- packages/sandbox/apps/googlediff.tsx
reusable select, select has fixed max height (scroll), redesigned and refactored diff view
> GE-455, GE-456

- packages/editor/src/editor/Editor.tsx
- packages/editor/src/state/containers/router.ts
- packages/sandbox/apps/googleState.tsx
- packages/sandbox/helpers/FakeRouter.tsx
fixed node deselect on routing, fixed onRouteChange not firing when last state change was from routeState prop, added external router usecase to googleState sandbox
> GE-494-495-496

- packages/editor/src/Graf/Graf.tsx
- packages/editor/src/editor/code/CodePane.tsx
- packages/editor/src/shared/components/PaintNodes/PaintNode.tsx
- packages/editor/src/shared/hooks/io.tsx
- packages/editor/src/shared/hooks/useDebouncedValue.ts
code debounced save, changes in code are visible in activeNode now, paint node opacity bugfix after code change, removed keyboard save
> creatore refresh after code change

- packages/editor/src/Graf/Graf.tsx
created a toast with error info when user tries to dbl duplicate node. not know if this is enough. let me know if need to be replaced with other visual component
> allow multi duplication of node without error

- packages/editor/src/Graf/Graf.tsx
- packages/editor/src/Graf/Node/Field/ActiveField.tsx
- packages/editor/src/Relation/PanZoom/ControlsBar.tsx
- packages/editor/src/Relation/PanZoom/PanZoom.tsx
- packages/editor/src/Relation/shared/nodeFilter.ts
Miałam jakiś problem z vscodem i nie działało mi formatowanie na save. Tu mam taki zbiorczy fix formatowania dla ostatnich PRek. Sorki
> fix formatting

- packages/editor/src/shared/components/NewNode/NewNodeMenu.tsx
sprawdza nazwę z insensitive i typ, czyli jak jest już node type User to nie pozwoli stworzyć node type User drugiego ale też node type user. Jak ma patrzeć na case to wystarczy wywalić toLowerCase przy porównywaniu.
https://dbl-nodes-validation.graphql-editor-dev.pages.dev/
> Double nodes validation

- packages/editor/src/Graf/Node/ActiveNode/TopNodeMenu.tsx
Robię PR, sprawdzaj kod i daj appr lub komentarz. Jak zrobisz approve to ja daje znak że można branch testing do tego zrobić. Jak branch testing przejdzie dopiero mergujemy. Ogarnianie tego na basecamp raczej karkołomne. Ticket do tego https://3.basecamp.com/5657330/buckets/33764929/todos/6604644949#__recording_6762578383
https://not-allow-to-extend-extended.graphql-editor-dev.pages.dev/
> not allow to extend or duplicate extended

- packages/editor/src/Relation/PanZoom/LinesDiagram/Lines/Draw.tsx
- packages/editor/src/Relation/PanZoom/LinesDiagram/Lines/index.tsx
- packages/editor/src/Relation/PanZoom/LinesDiagram/LinesDiagram.tsx
- packages/editor/src/state/containers/relationNodes.tsx
- packages/editor/src/state/containers/trees/index.ts
https://draw-lines-implementing.graphql-editor-dev.pages.dev/
> Draw lines implementing

- packages/editor/src/shared/dialogs/ImportSchema.tsx
https://3.basecamp.com/5657330/buckets/33764929/todos/6823854021
https://clear-import-headers.graphql-editor-dev.pages.dev/
> clear values on modal state change

- packages/editor/src/Relation/PanZoom/LinesDiagram/LinesDiagram.tsx
- packages/editor/src/Relation/Relation.tsx
https://zoom-issues.graphql-editor-dev.pages.dev
naprawa https://3.basecamp.com/5657330/buckets/33764929/todos/6697831245
plus revert zmiany wartości zoom
> zoom issues

- package-lock.json
- packages/editor-worker/package.json
- packages/editor/package.json
- packages/editor/src/Relation/PanZoom/LinesDiagram/Node/Field/index.tsx
- packages/editor/src/Relation/Relation.tsx
- packages/editor/src/editor/Editor.tsx
- packages/editor/src/editor/code/CodePane.tsx
- packages/editor/src/editor/code/guild/editor/LiveSchemaEditor.tsx
- packages/editor/src/editor/code/guild/editor/use-schema-services.tsx
- packages/editor/src/editor/code/index.ts
- packages/editor/src/shared/NodeNavigation/index.tsx
- packages/editor/src/shared/hooks/useDomManager.ts
- packages/editor/src/state/containers/relationNodes.tsx
- packages/editor/src/state/containers/trees/index.ts
- packages/sandbox/apps/livesocket.tsx
- packages/sandbox/package.json
- packages/socket-live-test/package.json
- packages/svg-ts-sync/package.json
https://focus-mode-extend-check.graphql-editor-dev.pages.dev
> Focus mode extend

- packages/editor/src/editor/Editor.tsx
- packages/editor/src/editor/menu/Menu.tsx
- packages/sandbox/apps/Pure.tsx
wyłączone na sandbox schema pure
https://disable-import-export.graphql-editor-dev.pages.dev/
> disable import export

- packages/editor/src/shared/NodeNavigation/NodeList.tsx
- packages/editor/src/shared/NodeNavigation/SingleNodeInList.tsx
https://context-enu-navigation.graphql-editor-dev.pages.dev/
> Context enu navigation

- packages/editor/src/Relation/PanZoom/LinesDiagram/LinesDiagram.tsx
https://fix-printing-connections.graphql-editor-dev.pages.dev/
> fix printing connections

- packages/editor/src/Relation/PanZoom/PanZoom.tsx
- packages/editor/src/Relation/Relation.tsx
do tego issue https://3.basecamp.com/5657330/buckets/33764929/todos/7259877064
> fix connection lines display when clearing schema

- packages/editor/src/editor/Editor.tsx
- packages/editor/src/editor/code/CodePane.tsx
- packages/editor/src/editor/files/FileTree.tsx
- packages/editor/src/editor/files/SingleFile.tsx
- packages/sandbox/apps/mergedLibraries.tsx
Nie wiem czy to jeszcze wszystkie zmiany. Moze cos jeszcze bede potrzebowac bo sprawdzeniu w desktopie. Wersje podbije sobie po mergu
disableCodePaneContextMenu - potrzebuje zeby w monaco edtytorze zablokowac context menu moim zdaniem niezbedne jak chcemy copy/paste zablokowac na demo
> Fixes on folders handling
